# Generated by Django 4.2.17 on 2025-08-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nd_api", "0010_clientdatadump_is_primary_key_uploaded"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacsClient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "handler_type",
                    models.IntegerField(choices=[(1, "DIR_HANDLER")], default=None),
                ),
                ("run_config", models.JSONField(default=dict)),
                ("register_date", models.DateField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pacs_client",
                        to="nd_api.clients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nd_patient_id", models.BigIntegerField(unique=True)),
                ("client_patient_id", models.BigIntegerField(unique=True)),
                ("offset_value", models.IntegerField(null=True)),
                (
                    "deid_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("total_study_count", models.IntegerField(default=0)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pacs_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="neuropacs.pacsclient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientStudy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_study_instance_uid", models.UUIDField(null=True)),
                ("nd_study_instance_uid", models.UUIDField(null=True)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                ("total_series_count", models.IntegerField(default=0)),
                (
                    "deid_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="neuropacs.patients",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientSeries",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_series_instance_uid", models.UUIDField(null=True)),
                ("nd_series_instance_uid", models.UUIDField(null=True)),
                ("total_instances_count", models.IntegerField(default=0)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                (
                    "deid_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="neuropacs.patientstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientInstance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("client_sop_instance_uid", models.UUIDField(null=True)),
                ("nd_sop_instance_uid", models.UUIDField(null=True)),
                (
                    "deid_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("original_file_path", models.TextField(default=None, null=True)),
                ("cloud_uploaded", models.BooleanField(default=False)),
                ("failure_remarks", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="neuropacs.patientseries",
                    ),
                ),
            ],
        ),
    ]
