# Generated by Django 4.2.17 on 2025-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuropacs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="nd_patient_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
