# Generated by Django 4.2.17 on 2025-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuropacs", "0002_alter_patients_nd_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinstance",
            name="client_sop_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="patientinstance",
            name="nd_sop_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="patientseries",
            name="client_series_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="patientseries",
            name="nd_series_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="patientstudy",
            name="client_study_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="patientstudy",
            name="nd_study_instance_uid",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
