# Generated by Django 4.2.17 on 2025-08-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuropacs", "0003_alter_patientinstance_client_sop_instance_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacsclient",
            name="inventory_creation_done",
            field=models.BooleanField(default=False),
        ),
    ]
