# Generated by Django 4.2.17 on 2025-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuropacs", "0004_pacsclient_inventory_creation_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinstance",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="patients",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="patientseries",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="patientstudy",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                ],
                default=0,
            ),
        ),
    ]
