# Generated by Django 4.2.17 on 2025-09-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neuropacs", "0005_alter_patientinstance_cloud_uploaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacsclient",
            name="patient_identifier_type",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
