"""
Django settings for deIdentification project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from jupyter_server.auth import passwd

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def is_true(value):
    if str(value).lower() in ["true", "1", "yes", "y"]:
        return True
    return False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-81e&%b$hwo15=#dwuv8pr(tz+8$eit5jr&_(ey=v@e3=&8u(b-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = is_true(os.environ.get("DEBUG", "true"))
DISABLE_AUTHENTICATION = is_true(os.environ.get("DISABLE_AUTHENTICATION", "True"))


ALLOWED_HOSTS = ["*"]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:13800", 
    "http://127.0.0.1:13800",
    "http://localhost:13000",
    "http://127.0.0.1:13000",
    "http://localhost:3001",
    "http://127.0.0.1:3001"
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:13800",
    "http://127.0.0.1:13800",
    "http://localhost:13000",
    "http://127.0.0.1:13000",
    "http://localhost:3001",
    "http://127.0.0.1:3001"
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "cache-control",
    "pragma",
    "api_version",
    "user_id",
    "x-forwarded-for",
    "x-forwarded-proto",
    "x-real-ip",
    "connection",
    "upgrade",
    "sec-websocket-key",
    "sec-websocket-version",
    "sec-websocket-protocol",
    "sec-websocket-extensions"
]

# Additional CORS settings for better compatibility
CORS_PREFLIGHT_MAX_AGE = 86400
CORS_ALLOW_PRIVATE_NETWORK = True
CORS_EXPOSE_HEADERS = [
    "content-type",
    "x-csrftoken",
    "authorization",
    "api_version",
    "user_id"
]
CORS_ALLOW_CREDENTIALS = True

# CSRF settings
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'keycloakauth.utils.IsAuthenticated',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "channels",
    "deIdentification",
    "nd_api",
    "nd_api_v2",
    "rest_framework",
    "worker",
    "keycloakauth",
    "corsheaders",
    "neuropacs",
    "ndwebsocket",
    "phi_analyzer"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "deIdentification.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "deIdentification.wsgi.application"
ASGI_APPLICATION = "deIdentification.asgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


BATCH_SIZE_DURING_DE_IDENTIFICATION = os.environ.get("BATCH_SIZE_DURING_DE_IDENTIFICATION", 10000)
PATIENT_ID_PREFIX = 10000000

# Jupyter Lab settings
NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8888",
    "--NotebookApp.password",
    passwd("ND@123"),
]

CREATE_SAVEPOINT_IN_TRANSACTION = is_true(
    os.getenv("CREATE_SAVEPOINT_IN_TRANSACTION", True)
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DE_IDENTIFICATION_DB_NAME", "dcnd_inc_prod"),
        "USER": os.getenv("DE_IDENTIFICATION_DB_USER", "postgres"),
        "PASSWORD": os.getenv("DE_IDENTIFICATION_DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DE_IDENTIFICATION_DB_HOST", "localhost"),
        "PORT": os.getenv("DE_IDENTIFICATION_DB_PORT", 5432),
        "CONN_MAX_AGE": os.getenv("CONN_MAX_AGE", 69000),
    }
}
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 13169)],
        },
    }
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Add a global templates directory if needed
        "APP_DIRS": True,  # Ensure this is True to enable app-specific templates
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "localhost-dev-client")
KEYCLOAK_REALM_NAME = os.environ.get("KEYCLOAK_REALM_NAME", "localhost-dev")
KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "p4BoX25BUe37K9b7gCuo4pL8vwdnUPf8")
KEYCLOAK_URI = os.environ.get("KEYCLOAK_URI", "http://localhost:9090/")
KEYCLOAK_ADMIN_USERNAME = os.environ.get("KEYCLOAK_ADMIN_USERNAME", "rohit")
KEYCLOAK_ADMIN_PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "rohit")


DATA_DUMP_DESTINATION_PATH = os.environ.get("DATA_DUMP_DESTINATION_PATH", "/srv/data/dump_data")

CLOUD_BUCKET_NAME = os.environ.get("CLOUD_BUCKET_NAME")
CLIENT_NAME = os.environ.get("CLIENT_NAME", "DEIDENTIFICATION_CLIENT")


DEFAULT_OFFSET_VALUE = int(os.environ.get("DEFAULT_OFFSET_VALUE", 34))
STATS_GENERATION_MAX_WORKER_COUNT = int(os.environ.get("STATS_GENERATION_MAX_WORKER_COUNT", 30))
MAX_FAILURE_COUNT=int(os.environ.get("MAX_FAILURE_COUNT", 1))

DB_CACHER=os.environ.get("DB_CACHER", "TEST")
REDIS_HOST=os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT=os.environ.get("REDIS_PORT", 6379)
REDIS_DB=os.environ.get("REDIS_DB", "0")

# comma sepearted column names
# PATIENTID_COLUMNS=os.environ.get("PATIENTID_COLUMNS", "(PATIENTID, Integer), (PID, Integer), (PROFILEID, Integer)")
PATIENTID_COLUMNS=os.environ.get("PATIENTID_COLUMNS", "(PATIENTID, Integer), (CHARTID, Integer)")

# for alert on gcp space
ENABLE_FAILURE_ALERT=is_true(os.environ.get("ENABLE_FAILURE_ALERT", "False"))
SYSTEM_IDENTIFIER=os.environ.get("SYSTEM_IDENTIFIER", "ROHIT.LOCAL")
GCP_ALERT_WEBHOOK=os.environ.get("GCP_ALERT_WEBHOOK", "")


## for pacs data
PACS_DATA_SAVE_PATH=os.environ.get("PACS_DATA_SAVE_PATH", '/tmp/neurodiscovery/pacs')

QC_READ_LIMIT=int(os.environ.get("QC_READ_LIMIT", 10000))

WEBSOCKET_EVENT_ENABLED=is_true(os.environ.get("WEBSOCKET_EVENT_ENABLED", "True"))

CORS_ALLOW_ALL_ORIGINS = True      # any domain can access
CORS_ALLOW_CREDENTIALS = True      # if you want cookies/Authorization headers
CORS_ALLOW_HEADERS = ["*"]         # allow all headers
CORS_ALLOW_METHODS = ["*"]         # allow all HTTP methods

LOGS_DIR = os.environ.get("LOGS_DIR", "/tmp/neurodiscovery/logs")

INCREMENTAL_PROCESS_TYPE = 'athenaone'

