# Generated by Django 4.2.17 on 2025-07-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200, unique=True)),
                ('emr_type', models.CharField(max_length=200, unique=True)),
                ('config', models.JSONField()),
                ('mapping_db_config', models.JSONField(default=dict)),
                ('master_db_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoreRowsDeIdentificaiton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=200)),
                ('row', models.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableDEIDStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('failure_remarks', models.JSONField(default=dict)),
                ('deid_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (-1, 'Failed')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TableEmbeddingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_embd_done', models.BooleanField(default=False)),
                ('failure_remarks', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TableGCPStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_uploaded', models.IntegerField(choices=[(1, 'Not moved'), (2, 'Moved'), (-1, 'Failed')], default=1)),
                ('md5sum', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_remarks', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columns', models.JSONField(default=dict)),
                ('primary_key', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TableQCStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qc_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (-1, 'Failed')], default=0)),
                ('qc_config', models.JSONField(default=dict)),
                ('qc_result', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDataDump',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dump_name', models.CharField(max_length=200, unique=True)),
                ('source_db_config', models.JSONField(default=dict)),
                ('run_config', models.JSONField(default=dict)),
                ('pii_config', models.JSONField(default=dict)),
                ('qc_config', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (-1, 'Failed')], default=0)),
                ('stats_generated_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed'), (-1, 'Failed')], default=0)),
                ('dump_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumps', to='nd_api.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, max_length=255)),
                ('rows_count', models.IntegerField(null=True)),
                ('table_details_for_ui', models.JSONField(default=dict)),
                ('is_phi_marking_done', models.BooleanField(default=False)),
                ('is_phi_marking_locked', models.BooleanField(null=True)),
                ('run_config', models.JSONField(default=dict)),
                ('is_required', models.BooleanField(default=True)),
                ('deid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='nd_api.tabledeidstatus')),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='nd_api.clientdatadump')),
                ('embd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='nd_api.tableembeddingstatus')),
                ('gcp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='nd_api.tablegcpstatus')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='nd_api.tablemetadata')),
                ('qc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='nd_api.tableqcstatus')),
            ],
            options={
                'indexes': [models.Index(fields=['table_name', 'dump'], name='nd_api_tabl_table_n_921182_idx')],
                'unique_together': {('table_name', 'dump')},
            },
        ),
    ]
