# Generated by Django 4.2.17 on 2025-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ignorerowsdeidentificaiton",
            old_name="db_name",
            new_name="dump_name",
        ),
        migrations.AlterField(
            model_name="clients",
            name="emr_type",
            field=models.CharField(max_length=200),
        ),
    ]
