# Generated by Django 4.2.17 on 2025-07-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0002_rename_db_name_ignorerowsdeidentificaiton_dump_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
