# Generated by Django 4.2.17 on 2025-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0003_alter_clients_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdatadump",
            name="dump_stats",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="clientdatadump",
            name="global_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="clientdatadump",
            name="secondary_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="ignorerowsdeidentificaiton",
            name="row",
            field=models.JSONField(default=dict),
        ),
    ]
