# Generated by Django 4.2.17 on 2025-07-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0004_clientdatadump_dump_stats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdatadump",
            name="global_config",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="clientdatadump",
            name="secondary_config",
            field=models.JSONField(default=list),
        ),
    ]
