# Generated by Django 4.2.17 on 2025-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0005_alter_clientdatadump_global_config_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tableembeddingstatus",
            name="is_embd_done",
        ),
        migrations.AddField(
            model_name="tableembeddingstatus",
            name="embd_stats",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="tablegcpstatus",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not moved"),
                    (2, "Moved"),
                    (-1, "Failed"),
                    (1, "In Process"),
                ],
                default=0,
            ),
        ),
    ]
