# Generated by Django 4.2.17 on 2025-08-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0006_remove_tableembeddingstatus_is_embd_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="client_presetup_config_configured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clients",
            name="presetup_remarks",
            field=models.JSONField(default=dict),
        ),
    ]
