# Generated by Django 4.2.17 on 2025-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0007_clients_client_presetup_config_configured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdatadump",
            name="is_dump_processing_done",
            field=models.BooleanField(default=False),
        ),
    ]
