# Generated by Django 4.2.17 on 2025-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0008_clientdatadump_is_dump_processing_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="patient_identifier_columns",
            field=models.JSONField(default=list),
        ),
    ]
