# Generated by Django 4.2.17 on 2025-08-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0009_clients_patient_identifier_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdatadump",
            name="is_primary_key_uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
