# Generated by Django 4.2.17 on 2025-10-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0010_clientdatadump_is_primary_key_uploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
