# Generated by Django 4.2.17 on 2025-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api", "0011_table_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabledeidstatus",
            name="deid_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (3, "Interrupted"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="tableembeddingstatus",
            name="embd_stats",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (3, "Interrupted"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="tablegcpstatus",
            name="cloud_uploaded",
            field=models.IntegerField(
                choices=[
                    (0, "Not moved"),
                    (2, "Moved"),
                    (-1, "Failed"),
                    (1, "In Process"),
                    (3, "Interrupted"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="tableqcstatus",
            name="qc_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (3, "Interrupted"),
                ],
                default=0,
            ),
        ),
    ]
