t = TableDetailsModel.objects.get(table_name="users")
t.table_details_for_ui = {
    "batch_size": 1000,
    "ignore_rows": {},
    "columns_details": [
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "uid",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "PATIENT_ID_PATIENTID",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PATIENT_NAME",
            "column_name": "uname",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PASSWORD",
            "column_name": "upwd",
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "udesc",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "ROOM_NUMBER",
            "column_name": "uroomno",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PHONE_NUMBER",
            "column_name": "umobileno",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PAGER_NUMBER",
            "column_name": "upagerno",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PATIENT_NAME",
            "column_name": "ufname",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PATIENT_NAME",
            "column_name": "uminitial",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PATIENT_NAME",
            "column_name": "ulname",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "EMAIL_ID",
            "column_name": "uemail",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "UWEBPAGE",
            "column_name": "uwebpage",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PO_BOX_STREET",
            "column_name": "upaddress",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "CITY",
            "column_name": "upcity",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "upstate",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PHONE_NUMBER",
            "column_name": "upPhone",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "UserType",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "zipcode",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "ZIP_CODE",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "dob",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "PATIENT_DOB",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "SSN",
            "column_name": "ssn",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "mflag",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "updid",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "cdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "DATE_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "cdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "eq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "STATIC_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "mdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "DATE_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "mdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "eq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "STATIC_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "sex",
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PO_BOX_STREET",
            "column_name": "upaddress2",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "SUFFIX",
            "column_name": "suffix",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PREFIX",
            "column_name": "prefix",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "INITIALS",
            "column_name": "initials",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "ptDob",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "PATIENT_DOB",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "delFlag",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "VMID",
            "column_name": "vmid",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "status",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "webenabled",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "websync",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "changePass",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "primaryservicelocation",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "NAME",
            "column_name": "upreviousname",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "IsResource",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EligibilityStatus",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "OSUUserType",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "DefApptProvForResource",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "locked",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EncEligibilityStatus2",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EligibilityMessage2",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EncEligibilityStatus3",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EligibilityMessage3",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EncEligibilityStatus",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EligibilityMessage",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "AllFacilities",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "Emrsex",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "CountryCode",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "transgender",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EnterpriseId",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "gestationalAge",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "NOTES",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "timeofbirth",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "LANGUAGE",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "county",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "isCredentialed",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EncEligibilityStatus4",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "EligibilityMessage4",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "ACOUserType",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "credentialschange",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "scheduling_placeholder",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "JobTitle",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "IsFreshScan",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "EMPCODE",
            "column_name": "empcode",
            "ignore_column": {
                "columns": [
                    {"name": "UserType", "value": 3, "condition": "neq"},
                    {"name": "UserType", "value": 4, "condition": "neq"},
                ],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "isBMHashed",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "displayresourcenameonpn",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "PASSWORD",
            "column_name": "epcsPassword",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "MASK",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "newUserFlag",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "RxSuffix",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "RxJobTitle",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "Effectivestartdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "DATE_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "Effectivestartdate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "eq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "STATIC_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "Effectiveenddate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "neq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "DATE_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "Effectiveenddate",
            "ignore_column": {
                "columns": [{"name": "UserType", "value": 3, "condition": "eq"}],
                "operation": "and",
            },
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "STATIC_OFFSET",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "countycode",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "userAccess",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "is_patientsafetyofficer",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "healowPlusAccess",
            "ignore_column": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
    ],
    "reference_mapping": {},
    "reference_enc_id_column": None,
    "reference_patient_id_column": "uid",
    "consider_if_mapping_not_present": True,
}

t.save()
