SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    '' AS IS_PHI,
    '' AS DE_IDENTIFICATION_RULE,
    '' AS MASK_VALUE,
    '' AS REFERENCE_PATIENT_ID,
    '' AS REFERENCE_ENCOUNTER_ID
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'mavenclad'
ORDER BY TABLE_NAME, ORDINAL_POSITION;

