# Generated by Django 4.2.17 on 2025-01-24 11:35

from django.db import migrations, models
import django.db.models.deletion
import keycloakauth.rolemodel


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "session_id",
                    models.CharField(default=None, max_length=200, null=True),
                ),
                ("is_authenticated", models.BooleanField(default=False)),
                ("access_token", models.TextField(default=None, null=True)),
                ("refresh_token", models.TextField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "permissions",
                    models.JSONField(
                        default=keycloakauth.rolemodel.get_default_permissions
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nd_role",
                        to="keycloakauth.authuser",
                    ),
                ),
            ],
        ),
    ]
