# Generated by Django 4.2.17 on 2025-01-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.IntegerField(default=0)),
                (
                    "reference_uuid",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("adjacency_list", models.JSONField(default=dict)),
                ("soft_delete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("arguments", models.JSONField(default=dict)),
                ("remarks", models.JSONField(default=dict)),
                ("status", models.IntegerField(db_index=True, default=0)),
                ("num_dependencies_total", models.IntegerField(default=0)),
                (
                    "num_dependencies_pending",
                    models.IntegerField(db_index=True, default=0),
                ),
                ("timeout", models.IntegerField(default=60)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("back_off", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("soft_delete", models.BooleanField(db_index=True, default=False)),
                ("repeat", models.BooleanField(default=False)),
                ("repeat_period", models.IntegerField(default=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("runtime", models.IntegerField(default=-1, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("max_failure_count", models.IntegerField(default=5)),
                ("back_off_algo", models.TextField(default="")),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="worker.chain",
                    ),
                ),
            ],
        ),
    ]
