# Generated by Django 4.2.17 on 2025-09-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worker", "0001_initial"),
        ("nd_api", "0010_clientdatadump_is_primary_key_uploaded"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHIAnalysisSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Analysis configuration parameters"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, help_text="Current processing step", max_length=200
                    ),
                ),
                ("total_tables", models.IntegerField(default=0)),
                ("processed_tables", models.IntegerField(default=0)),
                ("total_columns", models.IntegerField(default=0)),
                ("phi_columns_found", models.IntegerField(default=0)),
                ("validation_passed", models.IntegerField(default=0)),
                ("validation_failed", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "output_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to generated CSV file",
                        max_length=500,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if analysis failed"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phi_analysis_sessions",
                        to="nd_api.clients",
                    ),
                ),
                (
                    "dump",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phi_analysis_sessions",
                        to="nd_api.clientdatadump",
                    ),
                ),
                (
                    "task_chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="worker.chain",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PHITableResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(db_index=True, max_length=200)),
                (
                    "table_index",
                    models.IntegerField(help_text="Order of table in analysis"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Table processing progress (0-100)"
                    ),
                ),
                ("total_columns", models.IntegerField(default=0)),
                ("phi_columns", models.IntegerField(default=0)),
                ("validation_passed", models.IntegerField(default=0)),
                ("validation_failed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_results",
                        to="phi_analyzer.phianalysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["table_index"],
            },
        ),
        migrations.CreateModel(
            name="PHIColumnResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("column_name", models.CharField(db_index=True, max_length=200)),
                (
                    "is_phi",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "phi_rule",
                    models.CharField(
                        blank=True, help_text="Applied PHI rule", max_length=100
                    ),
                ),
                (
                    "pipeline_remark",
                    models.TextField(
                        blank=True, help_text="Pipeline validation remarks"
                    ),
                ),
                (
                    "user_remarks",
                    models.TextField(blank=True, help_text="Manual user remarks"),
                ),
                (
                    "is_manually_verified",
                    models.BooleanField(
                        default=False, help_text="Manual verification completed status"
                    ),
                ),
                (
                    "verified_by",
                    models.CharField(
                        blank=True,
                        help_text="User who performed manual verification",
                        max_length=200,
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When manual verification was completed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "table_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_results",
                        to="phi_analyzer.phitableresult",
                    ),
                ),
            ],
            options={
                "ordering": ["column_name"],
            },
        ),
        migrations.CreateModel(
            name="PHIAnalysisProgress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("step_name", models.CharField(max_length=200)),
                (
                    "step_index",
                    models.IntegerField(help_text="Order of step in analysis"),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(help_text="Overall progress percentage"),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "details",
                    models.JSONField(default=dict, help_text="Additional step details"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="phi_analyzer.phianalysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Configuration name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Configuration description"),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="gpt-4", help_text="LLM model name", max_length=100
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.1, help_text="Temperature for model output (0-1)"
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        default=1000, help_text="Maximum tokens for model response"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=100, help_text="Sample size for analysis"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default configuration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this configuration is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="User who created this configuration",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_default"],
                        name="phi_analyze_is_acti_1e5391_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="phitableresult",
            index=models.Index(
                fields=["session", "status"], name="phi_analyze_session_e8f38a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phitableresult",
            index=models.Index(
                fields=["table_name", "status"], name="phi_analyze_table_n_63bb56_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phitableresult",
            unique_together={("session", "table_name")},
        ),
        migrations.AddIndex(
            model_name="phicolumnresult",
            index=models.Index(
                fields=["table_result", "is_phi"], name="phi_analyze_table_r_cd38b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="phicolumnresult",
            unique_together={("table_result", "column_name")},
        ),
        migrations.AddIndex(
            model_name="phianalysissession",
            index=models.Index(
                fields=["client", "status"], name="phi_analyze_client__b3388f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phianalysissession",
            index=models.Index(
                fields=["status", "created_at"], name="phi_analyze_status_453f1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phianalysisprogress",
            index=models.Index(
                fields=["session", "timestamp"], name="phi_analyze_session_2846ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phianalysisprogress",
            index=models.Index(
                fields=["step_index", "timestamp"],
                name="phi_analyze_step_in_99a59d_idx",
            ),
        ),
    ]
