# Generated by Django 4.2.17 on 2025-11-09 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientRunConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_configured", models.BooleanField(default=False)),
                ("patient_identifier_columns", models.JSONField(default=list)),
                ("admin_connection_str", models.CharField(max_length=255)),
                ("nd_patient_start_value", models.IntegerField(default=0)),
                ("default_offset_value", models.IntegerField(default=0)),
                ("enable_auto_qc", models.BooleanField(default=False)),
                ("enable_auto_gcp", models.BooleanField(default=False)),
                ("enable_auto_embd", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IncrementalQueue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("queue_name", models.CharField(max_length=255)),
                ("dump_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "queue_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                            (3, "Interupted"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MappingConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_configured", models.BooleanField(default=False)),
                ("mapping_config", models.JSONField(default=dict)),
                ("mapping_schema", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MasterTableConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_configured", models.BooleanField(default=False)),
                ("pii_tables_config", models.JSONField(default=dict)),
                ("pii_schema_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PIIMaskingConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_configured", models.BooleanField(default=False)),
                ("pii_masking_config", models.JSONField(default=dict)),
                ("secondary_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QCConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_configured", models.BooleanField(default=False)),
                ("qc_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TableDEIDStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("failure_remarks", models.JSONField(default=dict)),
                (
                    "deid_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                            (3, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableEmbeddingStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "embd_stats",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                            (3, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
                ("failure_remarks", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TableGCPStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cloud_uploaded",
                    models.IntegerField(
                        choices=[
                            (0, "Not moved"),
                            (2, "Moved"),
                            (-1, "Failed"),
                            (1, "In Process"),
                            (3, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
                ("md5sum", models.CharField(blank=True, max_length=255, null=True)),
                ("failure_remarks", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TableMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(db_index=True, max_length=255)),
                ("columns", models.JSONField(default=dict)),
                ("primary_key", models.JSONField(default=dict)),
                ("max_nd_auto_increment_id", models.IntegerField(default=0)),
                ("table_details_for_ui", models.JSONField(default=dict)),
                ("run_config", models.JSONField(default=dict)),
                ("is_required", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_phi_marking_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TableQCStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "qc_status",
                    models.IntegerField(
                        choices=[
                            (0, "Not Started"),
                            (1, "In Progress"),
                            (2, "Completed"),
                            (-1, "Failed"),
                            (3, "Interrupted"),
                        ],
                        default=0,
                    ),
                ),
                ("qc_config", models.JSONField(default=dict)),
                ("qc_result", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nd_auto_increment_start_value", models.IntegerField(default=0)),
                ("nd_auto_increment_end_value", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="nd_api_v2.tabledeidstatus",
                    ),
                ),
                (
                    "embd",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="nd_api_v2.tableembeddingstatus",
                    ),
                ),
                (
                    "gcp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="nd_api_v2.tablegcpstatus",
                    ),
                ),
                (
                    "incremental_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="nd_api_v2.incrementalqueue",
                    ),
                ),
                (
                    "metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="nd_api_v2.tablemetadata",
                    ),
                ),
                (
                    "qc",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table",
                        to="nd_api_v2.tableqcstatus",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["metadata"], name="nd_api_v2_t_metadat_ce0430_idx"
                    )
                ],
                "unique_together": {("metadata",)},
            },
        ),
    ]
