# Generated by Django 4.2.17 on 2025-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api_v2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrunconfig",
            name="ehr_type",
            field=models.CharField(
                choices=[
                    ("AnthenaOne", "anthenaone"),
                    ("eCW", "ecw"),
                    ("AthenPractice", "athenpractice"),
                ],
                default="AnthenaOne",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="clientrunconfig",
            name="nd_patient_start_value",
            field=models.BigIntegerField(default=0),
        ),
    ]
