# Generated by Django 4.2.17 on 2025-11-11 19:27

from django.db import migrations, models
import nd_api_v2.models.scheduler_config


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api_v2", "0002_clientrunconfig_ehr_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulerConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "run_config",
                    models.JSONField(
                        default=nd_api_v2.models.scheduler_config.default_run_config
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
