# Generated by Django 4.2.17 on 2025-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api_v2", "0003_schedulerconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incrementalqueue",
            name="queue_status",
            field=models.IntegerField(
                choices=[
                    (0, "Not Started"),
                    (1, "In Progress"),
                    (2, "Completed"),
                    (-1, "Failed"),
                    (3, "Interupted"),
                    (4, "Manualy Skipped"),
                ],
                default=0,
            ),
        ),
    ]
