# Generated by Django 4.2.17 on 2025-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api_v2", "0004_alter_incrementalqueue_queue_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoreRowsDeIdentificaiton",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("queue_id", models.IntegerField()),
                ("table_name", models.CharField(max_length=200)),
                ("row", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
