# Generated by Django 4.2.17 on 2025-11-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nd_api_v2", "0005_ignorerowsdeidentificaiton"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="table",
            name="nd_api_v2_t_metadat_ce0430_idx",
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="table",
            name="incremental_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="nd_api_v2.incrementalqueue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("metadata", "incremental_queue")},
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["metadata", "incremental_queue"],
                name="nd_api_v2_t_metadat_24f420_idx",
            ),
        ),
    ]
