version: "3.8"

services:
  de-identification-ui:
    container_name: portal_ui
    image: deidentification_portal_ui:${DE_IDENTIFICATION_TAG_UI}
    ports:
      - "${DE_IDENTIFICATION_API_PORT_UI}:3000"
    restart: always
  de-identification-api:
    container_name: api
    image: deidentification_portal:${DE_IDENTIFICATION_TAG}
    ports:
      - "${DE_IDENTIFICATION_API_PORT}:8000"
    env_file:
      - ${DE_IDENTIFICATION_ENV_FILE}
    command: bash /nd_deployment/run.sh
    restart: always
    volumes:
      - ${SETUP_CONFIG_PATH}:/nd_deployment/setup_config.json
    depends_on:
      de-identification-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/auth/login || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  de-identification-worker:
    container_name: worker
    image: deidentification_portal:${DE_IDENTIFICATION_TAG}
    env_file:
      - ${DE_IDENTIFICATION_ENV_FILE}
    command: python3.10 ./deIdentification/manage.py start_worker
    restart: always
    depends_on:
        de-identification-db:
          condition: service_healthy
        de-identification-api:
          condition: service_healthy
  de-identification-notebook:
    container_name: notebook
    image: deidentification_portal:${DE_IDENTIFICATION_TAG}
    ports:
      - "${DE_IDENTIFICATION_NOTEBOOK_PORT}:8888"
    env_file:
      - ${DE_IDENTIFICATION_ENV_FILE}
    working_dir: /NOTEBOOK
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
    restart: always
  de-identification-db:
    image: postgres:15
    container_name: deidentification_db
    environment:
      - POSTGRES_DB=${DE_IDENTIFICATION_DB_NAME}
      - POSTGRES_USER=${DE_IDENTIFICATION_DB_USER}
      - POSTGRES_PASSWORD=${DE_IDENTIFICATION_DB_PASSWORD}
    ports:
      - "6545:5432"
    volumes:
      - de_identification_portal_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deid_user"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  de_identification_portal_data:
    external: true