version: "3.8"

services:
  de-identification-incremental:
    image: postgres:15
    container_name: postgres_deidentification_incremental
    environment:
      - POSTGRES_DB=deidentification_incremental
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9743:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: