# Generated by Django 4.2.17 on 2025-09-05 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('task_status', 'Task Status'), ('task_progress', 'Task Progress'), ('task_error', 'Task Error'), ('system_alert', 'System Alert'), ('info', 'Information'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=10)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('task_name', models.CharField(blank=True, help_text='Name of the task this notification relates to', max_length=100, null=True)),
                ('progress', models.IntegerField(blank=True, help_text='Progress percentage (0-100) if applicable', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code if this is an error notification', max_length=50, null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional details as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification expires (optional)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type'], name='ndwebsocket_notific_b275f0_idx'), models.Index(fields=['created_at'], name='ndwebsocket_created_e4c657_idx'), models.Index(fields=['status'], name='ndwebsocket_status_205052_idx')],
            },
        ),
    ]
