CREATE TABLE deidentified.`cpc_measure_config` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Measure_Id` varchar(20) DEFAULT NULL,
  `Num_Desc` text,
  `Den_Desc` text,
  `Excl_Desc` text,
  `Inactive_Flg` smallint DEFAULT NULL,
  `Publish_Flg` smallint DEFAULT NULL,
  `Num_Key` varchar(500) DEFAULT NULL,
  `Den_Key` varchar(500) DEFAULT NULL,
  `Excl_Key` varchar(500) DEFAULT NULL,
  `Starttime` varchar(100) DEFAULT NULL,
  `Endtime` varchar(100) DEFAULT NULL,
  `MeasureLevel` int DEFAULT NULL,
  `Exception_Desc` varchar(8000) DEFAULT NULL,
  `threshold` varchar(50) DEFAULT NULL,
  `Num_Exclusion` varchar(8000) DEFAULT NULL,
  `IPP_Desc` varchar(8000) DEFAULT NULL,
  `Version` varchar(25) DEFAULT NULL,
  `optionid` int DEFAULT NULL,
  `ecwstructid` int DEFAULT NULL,
  `nd_auto_increment_id` bigint DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UX_cpc_measure_config_measure_id` (`Measure_Id`)
) ENGINE=InnoDB AUTO_INCREMENT=309 DEFAULT CHARSET=latin1