CREATE TABLE deidentified.`cqm_pcfmeasureconfig` (
  `ConfigId` int NOT NULL AUTO_INCREMENT,
  `Measure_Id` varchar(20) DEFAULT NULL,
  `Year` varchar(4) DEFAULT NULL,
  `eCQM` tinyint(1) DEFAULT NULL,
  `MeasureVersion` varchar(8) DEFAULT NULL,
  `IPP_Desc` varchar(4000) DEFAULT NULL,
  `Num_Desc` varchar(4000) DEFAULT NULL,
  `Den_Desc` varchar(4000) DEFAULT NULL,
  `Excl_Desc` varchar(4000) DEFAULT NULL,
  `Excp_Desc` varchar(4000) DEFAULT NULL,
  `Inactive_Flg` tinyint(1) DEFAULT '0',
  `Publish_Flg` tinyint(1) DEFAULT '0',
  `inverse` tinyint(1) DEFAULT '0',
  `version` int DEFAULT NULL,
  `Threshold` float DEFAULT NULL,
  `decile_3_lb` float DEFAULT NULL,
  `decile_3_ub` float DEFAULT NULL,
  `decile_4_lb` float DEFAULT NULL,
  `decile_4_ub` float DEFAULT NULL,
  `decile_5_lb` float DEFAULT NULL,
  `decile_5_ub` float DEFAULT NULL,
  `decile_6_lb` float DEFAULT NULL,
  `decile_6_ub` float DEFAULT NULL,
  `decile_7_lb` float DEFAULT NULL,
  `decile_7_ub` float DEFAULT NULL,
  `decile_8_lb` float DEFAULT NULL,
  `decile_8_ub` float DEFAULT NULL,
  `decile_9_lb` float DEFAULT NULL,
  `decile_9_ub` float DEFAULT NULL,
  `decile_10_lb` float DEFAULT NULL,
  `decile_10_ub` float DEFAULT NULL,
  `nd_auto_increment_id` bigint DEFAULT NULL,
  PRIMARY KEY (`ConfigId`),
  UNIQUE KEY `UX_cqm_pcfMeasureConfig_measure_id_year` (`Measure_Id`,`Year`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1