
CREATE TABLE emd_serono_master.`master_insurance_table_2` (
  `patient_id` int NOT NULL,
  `hcfa_PName` varchar(255) DEFAULT NULL,
  `hcfa_InsuredName` varchar(255) DEFAULT NULL,
  `hcfa_InsuredId` varchar(50) DEFAULT NULL,
  `hcfa_PAddressStreet` varchar(255) DEFAULT NULL,
  `hcfa_PAddressCity` varchar(255) DEFAULT NULL,
  `hcfa_InsuredAddStreet` varchar(255) DEFAULT NULL,
  `hcfa_InsuredAddCity` varchar(255) DEFAULT NULL,
  `hcfa_NameRef` varchar(255) DEFAULT NULL,
  `hcfa_SSN` varchar(20) DEFAULT NULL,
  `hcfa_EmpOrSchoolName` varchar(100) DEFAULT NULL,
  `hcfa_InsurancePlan` varchar(100) DEFAULT NULL,
  `hcfa_OtherInsuredName` varchar(255) DEFAULT NULL,
  `hcfa_OtherEmpName` varchar(255) DEFAULT NULL,
  `hcfa_OtherInsuranceName` varchar(255) DEFAULT NULL,
  `hcfa_PayorName1` varchar(255) DEFAULT NULL,
  `hcfa_PayorName2` varchar(255) DEFAULT NULL,
  `hcfa_PayorName3` varchar(255) DEFAULT NULL,
  `hcfa_PayorAddress11` varchar(100) DEFAULT NULL,
  `hcfa_PayorAddress12` varchar(100) DEFAULT NULL,
  `hcfa_PayorAddress13` varchar(100) DEFAULT NULL,
  `hcfa_PayorAddress21` varchar(100) DEFAULT NULL,
  `hcfa_PayorAddress22` varchar(100) DEFAULT NULL,
  `hcfa_PayorAddress23` varchar(100) DEFAULT NULL,
  `hcfa_PayorCity1` varchar(255) DEFAULT NULL,
  `hcfa_PayorZip1` varchar(255) DEFAULT NULL,
  `hcfa_PayorCity2` varchar(255) DEFAULT NULL,
  `hcfa_PayorZip2` varchar(255) DEFAULT NULL,
  `hcfa_PayorCity3` varchar(255) DEFAULT NULL,
  `hcfa_PayorZip3` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




insert into emd_serono_master.`master_insurance_table_2`
select b.PatientId as patient_id,
 a.SSN as hcfa_SSN,
 a.PName as hcfa_PName, 
 a.NameRef as hcfa_NameRef,
 a.InsuredId as hcfa_InsuredId,
 a.PayorZip1 as hcfa_PayorZip1,
 a.PayorZip2 as hcfa_PayorZip2,
 a.PayorZip3 as hcfa_PayorZip3,
 a.PayorCity1 as hcfa_PayorCity1,
 a.PayorCity2 as hcfa_PayorCity2,
 a.PayorCity3 as hcfa_PayorCity3,
 a.PayorName1 as hcfa_PayorName1,
 a.PayorName2 as hcfa_PayorName2,
 a.PayorName3 as hcfa_PayorName3,
 a.InsuredName as hcfa_InsuredName, 
 a.OtherEmpName as hcfa_OtherEmpName,
 a.PAddressCity as hcfa_PAddressCity,
 a.InsurancePlan as hcfa_InsurancePlan,
 a.InsuredAddCity as hcfa_InsuredAddCity,
 a.PAddressStreet as hcfa_PAddressStreet,
 a.PayorAddress11 as hcfa_PayorAddress11,
 a.PayorAddress12 as hcfa_PayorAddress12,
 a.PayorAddress13 as hcfa_PayorAddress13,
 a.PayorAddress21 as hcfa_PayorAddress21,
 a.PayorAddress22 as hcfa_PayorAddress22,
 a.PayorAddress23 as hcfa_PayorAddress23,
 a.EmpOrSchoolName as hcfa_EmpOrSchoolName,
 a.InsuredAddStreet as hcfa_InsuredAddStreet,
 a.OtherInsuredName as hcfa_OtherInsuredName,
 a.OtherInsuranceName as hcfa_OtherInsuranceName
 from dent_emd_serono.hcfa a
inner join dent_emd_serono.edi_invoice b on a.invid = b.id;