CREATE TABLE deidentified.inventory_product (
    Id INT NOT NULL,
    Name VARCHAR(255),
    Description TEXT,
    Barcode VARCHAR(255),
    Category_Id INT,
    IsDiscontinued TINYINT,
    OrderQtyUnit VARCHAR(255),
    OrderQty DECIMAL(13,4),
    UnitQtyUnit VARCHAR(255),
    UnitQty DECIMAL(13,4),
    UsageQtyUnit VARCHAR(255),
    HasSalesTax TINYINT,
    HasCosmeticTax TINYINT,
    HasCustomTax TINYINT,
    CPT_Id INT,
    CPT_Code VARCHAR(255),
    CPT_Description VARCHAR(255),
    CPT_Price DECIMAL(13,4),
    HasSerialNo TINYINT,
    HasExpiryDate TINYINT,
    SalesOrderPrice DECIMAL(13,4),
    SalesUnitPrice DECIMAL(13,4),
    SalesUsagePrice DECIMAL(13,4),
    AlertForOrderQty DECIMAL(13,4),
    AlertForUnitQty DECIMAL(13,4),
    AlertForUsageQty DECIMAL(13,4),
    DefaultOrderQty DECIMAL(13,4),
    DefaultUnitQty DECIMAL(13,4),
    DefaultUsageQty DECIMAL(13,4),
    AlertBeforeExpiryDate INT,
    IsDeleted TINYINT,
    UpdatedBy INT,
    UpdatedOn DATETIME,
    Manufacturer_Id INT,
    ImgSrc VARCHAR(255),
    Manufacturer VARCHAR(255),
    itemId INT,
    catId INT,
    IsRx TINYINT,
    Rx_CatItemId INT,
    Rx_CatItemName VARCHAR(255),
    Rx_ItemId INT,
    Rx_ItemName VARCHAR(255),
    Rx_Dosage VARCHAR(255),
    Rx_NDCCode VARCHAR(255),
    isLabsReports TINYINT,
    labsReports_Id INT,
    generic VARCHAR(255),
    Rx_Strength VARCHAR(255),
    Rx_Formulation VARCHAR(255),
    source TINYINT,
    Currency VARCHAR(255),
    isDiscountAllowed TINYINT,
    feeSchId INT,
    createdBy INT,
    createdOn DATETIME,
    isChargeable TINYINT,
    externalCode VARCHAR(255),
    isBySalesPrice TINYINT,
    isFromInterface TINYINT,
    cptFeeSchIds VARCHAR(255),
    hubId VARCHAR(255),
    item_number VARCHAR(255),
    model_number VARCHAR(255),
    stock_type TINYINT,
    isnondisposable TINYINT,
    UPC_Code VARCHAR(255),
    modality INT NOT NULL,
    uniqueKey TINYINT,
    uniqueCode VARCHAR(255),
    prodCustomField1 VARCHAR(255),
    prodCustomField2 VARCHAR(255),
    prodCustomField3 VARCHAR(255),
    prodCustomField4 VARCHAR(255),
    prodCustomField5 VARCHAR(255),
    country VARCHAR(255),
    styleId INT,
    type INT,
    isTrial TINYINT,
    modalityId INT,
    v_sku VARCHAR(55),
    haslatex TINYINT,
    hasimplant TINYINT,
    isService TINYINT,
    hasHazardousMaterial TINYINT,
    ptChargeableItemNumber VARCHAR(255),
    ptNonbillableExpense VARCHAR(255),
    ptNonbillableExpenseDescription VARCHAR(255),
    ptBillableExpense VARCHAR(255),
    ptBillableExpenseDescription VARCHAR(255),
    HasLotNo TINYINT,
    rx_class VARCHAR(255),
    brand_id INT,
    endDate DATETIME,
    eposDescription VARCHAR(255),
    iscustom TINYINT,
    Lifecycle_Status_Id INT,
    retailDept_Id INT,
    hasTaxExempt TINYINT NOT NULL,
    vat_code VARCHAR(255),
    costprice DECIMAL(12,2),
    contactlensType INT NOT NULL,
    tempProductId INT,
    lastsyncdate DATETIME NOT NULL,
    omtlensprice TINYINT NOT NULL,
    valId VARCHAR(50) NOT NULL,
    concentration VARCHAR(50) NOT NULL,
    rx_packsize DECIMAL(13,4) NOT NULL,
    rx_packageSizeUnitDesc VARCHAR(100),
    rx_secondaryNDC VARCHAR(20),
    rx_packsizeQty DECIMAL(13,4) NOT NULL,
    isManualyAddedNDC TINYINT,
    nd_auto_increment_id INT
);
